### PR TITLE
correction on change view

### PR DESCRIPTION
**Pull request by landlogicit**

### CODE REVIEW

**Comment by landlogicit** [comment]
please check and merge my  correction

**Comment by jochenwezel** [comment]
@landlogicit Thank you for posting you patch. Which issue do you fix with this change?

**Comment by landlogicit** [comment]
Error on change -view mode after click

**Comment by jochenwezel** [comment]
Which exception do you get and which value in in the cell?

**Comment by landlogicit** [comment]
Invalid cast exception. from System.DBNull to System.String on Contacts

**Comment by jochenwezel** [comment]
@landlogicit Thank you for bringing up this error to our attention and all your efforts. The bug is fixed and will be available soon via NuGet

**Pull request merged**
